# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/git/ENEL-453-Final-Project/ENEL 453 Final Project/ENEL 453 Final Project.runs/synth_1/.Xil/Vivado-37436-HXI-CENTRE/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      C:/git/ENEL-453-Final-Project/Data_Selecting_Mux.sv
      C:/git/ENEL-453-Final-Project/Data_Selection_Subsystem.sv
      C:/git/ENEL-453-Final-Project/Fall_Detector1.sv
      C:/git/ENEL-453-Final-Project/Fall_Detector2.sv
      C:/git/ENEL-453-Final-Project/Output_FSM.sv
      C:/git/ENEL-453-Final-Project/PWM_mux.sv
      C:/git/ENEL-453-Final-Project/R2R_mux.sv
      C:/git/ENEL-453-Final-Project/XADC_Mux.sv
      C:/git/ENEL-453-Final-Project/XADC_Subsystem.sv
      C:/git/ENEL-453-Final-Project/averager.sv
      C:/git/ENEL-453-Final-Project/averager_pwm.sv
      C:/git/ENEL-453-Final-Project/averager_subsystem.sv
      C:/git/ENEL-453-Final-Project/averager_subsystem2.sv
      C:/git/ENEL-453-Final-Project/bin_to_bcd.sv
      C:/git/ENEL-453-Final-Project/digit_multiplexor.sv
      C:/git/ENEL-453-Final-Project/downcounter.sv
      C:/git/ENEL-453-Final-Project/pwm.sv
      C:/git/ENEL-453-Final-Project/pwm_from_code.sv
      C:/git/ENEL-453-Final-Project/sar_adc_fsm.sv
      C:/git/ENEL-453-Final-Project/sawtooth_generator.sv
      C:/git/ENEL-453-Final-Project/sawtooth_generator2.sv
      C:/git/ENEL-453-Final-Project/sawtooth_subsystem.sv
      C:/git/ENEL-453-Final-Project/sawtooth_subsystem2.sv
      C:/git/ENEL-453-Final-Project/seven_segment_decoder.sv
      C:/git/ENEL-453-Final-Project/seven_segment_digit_selector.sv
      C:/git/ENEL-453-Final-Project/seven_segment_display_subsystem.sv
      C:/git/ENEL-453-Final-Project/switch_logic.sv
      C:/git/ENEL-453-Final-Project/Lab7_Top_Level.sv
    }
      rt::read_verilog {{C:/git/ENEL-453-Final-Project/ENEL 453 Final Project/ENEL 453 Final Project.runs/synth_1/.Xil/Vivado-37436-HXI-CENTRE/realtime/xadc_wiz_0_stub.v}}
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList {{C:/git/ENEL-453-Final-Project/ENEL 453 Final Project/ENEL 453 Final Project.runs/synth_1/.Xil/Vivado-37436-HXI-CENTRE/realtime/Lab7_Top_Level_synth.xdc}}
    rt::sdcChecksum
    set rt::top Lab7_Top_Level
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/git/ENEL-453-Final-Project/ENEL 453 Final Project/ENEL 453 Final Project.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/git/ENEL-453-Final-Project/ENEL 453 Final Project/ENEL 453 Final Project.runs/synth_1/.Xil/Vivado-37436-HXI-CENTRE/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
